"""SkillOpt Reporter — generates weekly optimization reports with metrics and trends.

TASK-067 — Consolidates optimization results across skills into a readable report.
"""

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from .skillopt_config import SkillOptConfig
from .skillopt import OptimizationResult

logger = logging.getLogger(__name__)


def generate_report(
    results: list[OptimizationResult],
    output_path: Optional[str] = None,
) -> str:
    """Generate a Markdown report from optimization results.

    Args:
        results: List of OptimizationResult from SkillOpt runs.
        output_path: Path to write report file. If None, auto-generates path.

    Returns:
        Path to the generated report file.
    """
    now = datetime.now(timezone.utc)
    report_date = now.strftime("%Y-%m-%d")

    # ── Build report ──
    lines = [
        f"# 🧠 SkillOpt Weekly Report — {report_date}",
        "",
        f"**Generated:** {now.isoformat()}",
        f"**Skills optimized:** {len(results)}",
        "",
        "---",
        "",
    ]

    # ── Summary table ──
    lines.append("## 📊 Summary")
    lines.append("")
    lines.append("| Skill | Initial | Final | Δ | Accepted | Rejected | Epochs |")
    lines.append("|-------|---------|-------|---|----------|----------|--------|")

    for r in results:
        delta = r.improvement
        emoji = "🟢" if delta > 0.03 else ("🟡" if delta > 0 else "🔴")
        lines.append(
            f"| {r.skill_name} | {r.initial_score:.3f} | {r.final_score:.3f} "
            f"| {emoji} {delta:+.3f} | {r.total_accepted_edits} | "
            f"{r.total_rejected_edits} | {len(r.epochs)} |"
        )

    lines.append("")

    # ── Per-skill details ──
    for r in results:
        lines.append(f"## {r.skill_name}")
        lines.append("")
        lines.append(f"- **Score:** {r.initial_score:.3f} → {r.final_score:.3f} ({r.improvement:+.3f})")
        lines.append(f"- **Edits:** {r.total_accepted_edits} accepted, {r.total_rejected_edits} rejected")
        lines.append(f"- **Duration:** {r.duration_seconds:.0f}s")
        lines.append(f"- **API calls:** {len(r.epochs)} epochs")
        lines.append("")

        if r.epochs:
            lines.append("### Epoch History")
            lines.append("")
            lines.append("| Epoch | Train Score | Cand. Score | Best Score | Acc | Rej |")
            lines.append("|-------|-------------|-------------|------------|-----|-----|")
            for e in r.epochs:
                acc = e.get("accepted_edits", 0)
                rej = e.get("rejected_edits", 0)
                lines.append(
                    f"| {e['epoch']} | {e.get('train_mean_score', 0):.3f} "
                    f"| {e.get('candidate_score', 0):.3f} "
                    f"| {e.get('best_score', 0):.3f} | {acc} | {rej} |"
                )
            lines.append("")

        if r.meta_patterns:
            lines.append("### Meta-Patterns")
            for p in r.meta_patterns:
                lines.append(f"- {p}")
            lines.append("")

        if r.rejection_buffer:
            lines.append(f"### Rejection Buffer ({len(r.rejection_buffer)} entries)")
            for rb in r.rejection_buffer[-3:]:
                edit = rb.get("edit", {})
                lines.append(f"- `{edit.get('op_type', '?')}` {edit.get('target_section', '?')[:60]}: {edit.get('reasoning', '?')[:100]}")
            lines.append("")

    # ── Recommendations ──
    lines.append("## 💡 Recommendations")
    lines.append("")

    improving = [r for r in results if r.improvement > 0.03]
    stagnant = [r for r in results if -0.01 <= r.improvement <= 0.03]
    degrading = [r for r in results if r.improvement < -0.01]

    if improving:
        lines.append(f"- ✅ **{len(improving)} skills improved significantly:** "
                     + ", ".join(r.skill_name for r in improving))
    if stagnant:
        lines.append(f"- ⚠️ **{len(stagnant)} skills stagnated:** "
                     + ", ".join(r.skill_name for r in stagnant)
                     + " — consider increasing epochs or adjusting edit budget")
    if degrading:
        lines.append(f"- 🔴 **{len(degrading)} skills degraded:** "
                     + ", ".join(r.skill_name for r in degrading)
                     + " — inspect rejection buffer for harmful patterns")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"*Report generated by SkillOpt Reporter at {now.isoformat()}*")
    lines.append("")

    report = "\n".join(lines)

    # ── Write to file ──
    out_path = Path(output_path) if output_path else Path(
        __file__
    ).resolve().parent / "skillopt_runs" / f"report_{report_date}.md"

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(report)
    logger.info(f"📄 Report saved: {out_path}")

    return str(out_path)


def load_results_from_dir(runs_dir: str) -> list[OptimizationResult]:
    """Load optimization results from a directory of result JSON files."""
    results = []
    runs = Path(runs_dir)

    if not runs.exists():
        logger.warning(f"Runs directory not found: {runs_dir}")
        return results

    for result_file in sorted(runs.rglob("optimization_result.json")):
        try:
            data = json.loads(result_file.read_text())
            result = OptimizationResult(
                skill_name=data.get("skill_name", "unknown"),
                initial_score=data.get("initial_score", 0.0),
                final_score=data.get("final_score", 0.0),
                best_score=data.get("best_score", 0.0),
                total_accepted_edits=data.get("total_accepted_edits", 0),
                total_rejected_edits=data.get("total_rejected_edits", 0),
                started_at=data.get("started_at", ""),
                finished_at=data.get("finished_at", ""),
            )
            result.epochs = data.get("epochs", [])
            result.meta_patterns = data.get("meta_patterns", [])
            result.rejection_buffer = data.get("rejection_buffer", [])
            results.append(result)
        except Exception as e:
            logger.warning(f"Failed to load {result_file}: {e}")

    return results
