"""Frontend codegen — core features → React pages + components."""

import logging
from pathlib import Path

from ..models import FunctionalSpec, TechnicalSpec

logger = logging.getLogger(__name__)


def generate_frontend(func: FunctionalSpec, tech: TechnicalSpec, output_dir: str) -> list[str]:
    """Generate React pages from core features spec.
    
    CodeGen 2.0: Includes i18n, themeSwitch, 10K quality components,
    lazy loading, and Vitest tests.
    """
    out = Path(output_dir)
    generated = []

    features = func.core_features or []
    pages_dir = out / "src/pages"
    comps_dir = out / "src/components"
    tests_dir = out / "src/__tests__"
    tests_dir.mkdir(parents=True, exist_ok=True)

    # ── 10K Components ──
    comps_to_generate = [
        ("ThemeToggle.tsx", _theme_toggle()),
        ("LanguageSwitcher.tsx", _language_switcher()),
        ("Card.tsx", _card_component()),
        ("Modal.tsx", _modal_component()),
        ("Table.tsx", _table_component()),
        ("Toast.tsx", _toast_component()),
        ("Button.tsx", _button_component()),
        ("Input.tsx", _input_component()),
        ("Skeleton.tsx", _skeleton_component()),
        ("EmptyState.tsx", _empty_state_component()),
        ("ErrorBoundary.tsx", _error_boundary()),
    ]
    for fname, content in comps_to_generate:
        p = comps_dir / fname
        p.write_text(content)
        generated.append(str(p))

    # ── Home page ──
    home = _home_page(features)
    p = pages_dir / "Home.tsx"
    p.write_text(home)
    generated.append(str(p))

    # ── Dashboard page ──
    dash = _dashboard_page(features)
    p = pages_dir / "Dashboard.tsx"
    p.write_text(dash)
    generated.append(str(p))

    # ── Feature-specific pages ──
    feature_names = []
    for f in features:
        fid = f.get("id", "")
        name = f.get("name", "")
        fname = _safe_filename(name or fid)
        feature_names.append(fname)
        page = _feature_page(f)
        p = pages_dir / f"{fname}.tsx"
        p.write_text(page)
        generated.append(str(p))

    # ── API hooks ──
    hooks = _api_hooks(features)
    p = out / "src/api/hooks.ts"
    p.write_text(hooks)
    generated.append(str(p))

    # ── Vitest tests ──
    vitest_tests = _generate_vitest_tests(feature_names)
    p = tests_dir / "components.test.tsx"
    p.write_text(vitest_tests)
    generated.append(str(p))

    logger.info(f"  ✦ Generated {len(generated)} frontend files")

    return generated


def _home_page(features: list[dict]) -> str:
    items = "\n".join(
        f'          <div className="bg-slate-800 rounded-xl p-6">\n'
        f'            <h3 className="text-lg font-semibold text-teal-400 mb-2">{f.get("name", "Feature")}</h3>\n'
        f'            <p className="text-sm text-slate-400">{f.get("description", "")}</p>\n'
        f'          </div>'
        for f in features[:6]
    )

    return f"""export default function Home() {{
  return (
    <div className="space-y-12">
      <section className="text-center py-16">
        <h1 className="text-5xl font-bold text-white mb-4">Welcome to Your MVP</h1>
        <p className="text-xl text-slate-400 max-w-2xl mx-auto">
          Generated by PitchForge — your idea, your product, fast.
        </p>
        <a
          href="/dashboard"
          className="inline-block mt-8 px-8 py-3 bg-teal-500 text-white font-medium rounded-lg hover:bg-teal-400 transition"
        >
          Get Started
        </a>
      </section>

      <section>
        <h2 className="text-2xl font-bold text-white mb-6">Core Features</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
{items}
        </div>
      </section>
    </div>
  )
}}
"""


def _dashboard_page(features: list[dict]) -> str:
    items = "\n".join(
        f'            <Link to="/{_safe_filename(f.get("name", f.get("id", "feature")))}" className="block bg-slate-800 rounded-xl p-6 hover:bg-slate-700 transition">\n'
        f'              <h3 className="text-lg font-semibold text-teal-400 mb-1">{f.get("name", "Feature")}</h3>\n'
        f'              <p className="text-sm text-slate-400">{f.get("description", "")[:80]}</p>\n'
        f'            </Link>'
        for f in features[:6]
    )

    return """import { Link } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import api from '../api/client'

export default function Dashboard() {
  const { data: health } = useQuery({
    queryKey: ['health'],
    queryFn: () => api.get('/health').then(r => r.data),
  })

  return (
    <div className="space-y-8">
      <div className="flex items-center justify-between">
        <h1 className="text-3xl font-bold text-white">Dashboard</h1>
        {health && (
          <span className="text-sm text-green-400">
            ● API {health.status || 'connected'}
          </span>
        )}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
""" + items + """
      </div>
    </div>
  )
}
"""


def _feature_page(feature: dict) -> str:
    name = feature.get("name", "Feature")
    desc = feature.get("description", "")
    criteria = feature.get("acceptance_criteria", [])

    criteria_items = "\n".join(
        f'              <li className="text-sm text-slate-300">✓ {c}</li>' for c in criteria[:5]
    )

    return f"""import {{ useQuery }} from '@tanstack/react-query'
import api from '../api/client'

export default function {_safe_filename(name)}Page() {{
  const {{ data, isLoading }} = useQuery({{
    queryKey: ['{_safe_filename(name).lower()}'],
    queryFn: () => api.get('/api/v1/{_safe_filename(name).lower()}').then(r => r.data),
    retry: false,
  }})

  return (
    <div className="space-y-6">
      <h1 className="text-3xl font-bold text-white">{name}</h1>
      <p className="text-slate-400">{desc}</p>

      <div className="bg-slate-800 rounded-xl p-6">
        <h2 className="text-lg font-semibold text-teal-400 mb-4">Data</h2>
        {{isLoading && <p className="text-slate-500">Loading...</p>}}
        {{data && (
          <pre className="text-sm text-slate-300 overflow-auto">
            {{JSON.stringify(data, null, 2)}}
          </pre>
        )}}
        {{!isLoading && !data && (
          <p className="text-sm text-slate-500">No data yet. Implement the API to see results here.</p>
        )}}
      </div>

      <div className="bg-slate-800 rounded-xl p-6">
        <h2 className="text-lg font-semibold text-teal-400 mb-4">Acceptance Criteria</h2>
        <ul className="space-y-2">
{criteria_items}
        </ul>
      </div>
    </div>
  )
}}
"""


def _api_hooks(features: list[dict]) -> str:
    return """import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import api from './client'

// Generic CRUD hooks — use these in your pages:
//
//   const { data, isLoading } = useList('users')
//   const { data } = useGet('users', 1)
//   const createMutation = useCreate('users')
//   const updateMutation = useUpdate('users')
//   const deleteMutation = useDelete('users')

export function useList(resource: string) {
  return useQuery({
    queryKey: [resource],
    queryFn: () => api.get(`/${resource}`).then(r => r.data),
  })
}

export function useGet(resource: string, id: number) {
  return useQuery({
    queryKey: [resource, id],
    queryFn: () => api.get(`/${resource}/${id}`).then(r => r.data),
  })
}

export function useCreate(resource: string) {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (data: unknown) => api.post(`/${resource}`, data),
    onSuccess: () => qc.invalidateQueries({ queryKey: [resource] }),
  })
}

export function useUpdate(resource: string) {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: ({ id, data }: { id: number; data: unknown }) =>
      api.patch(`/${resource}/${id}`, data),
    onSuccess: () => qc.invalidateQueries({ queryKey: [resource] }),
  })
}

export function useDelete(resource: string) {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (id: number) => api.delete(`/${resource}/${id}`),
    onSuccess: () => qc.invalidateQueries({ queryKey: [resource] }),
  })
}
"""


def _tailwind_css() -> str:
    return """@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  @apply bg-slate-900 text-slate-100;
  font-family: 'Inter', system-ui, sans-serif;
}
"""


def _tailwind_config() -> str:
    return """/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          400: '#2dd4bf',
          500: '#14b8a6',
          600: '#0d9488',
        },
      },
    },
  },
  plugins: [],
}
"""


def _postcss_config() -> str:
    return """export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
"""


def _safe_filename(name: str) -> str:
    """Convert feature name to PascalCase filename."""
    import re
    clean = re.sub(r'[^a-zA-Z0-9\s-]', '', name)
    words = clean.replace('-', ' ').split()
    return ''.join(w.capitalize() for w in words) if words else 'Feature'


def _generate_vitest_tests(feature_names: list[str]) -> str:
    """Generate Vitest unit tests for React components."""
    feature_imports = "\n".join(
        f"import {{ {n}Page }} from '../pages/{n}'"
        for n in feature_names[:4]
    )

    return f'''import {{ describe, it, expect }} from 'vitest'
import {{ render, screen }} from '@testing-library/react'
import {{ MemoryRouter }} from 'react-router-dom'
import {{ QueryClient, QueryClientProvider }} from '@tanstack/react-query'

// Components under test
import {{ Card }} from '../components/Card'
import {{ Button }} from '../components/Button'
import {{ Input }} from '../components/Input'
import {{ EmptyState }} from '../components/EmptyState'
import {{ Skeleton }} from '../components/Skeleton'
import {{ Modal }} from '../components/Modal'
{feature_imports if feature_imports else '// No feature pages yet'}

const queryClient = new QueryClient({{
  defaultOptions: {{ queries: {{ retry: false }} }},
}})

function Wrapper({{ children }}: {{ children: React.ReactNode }}) {{
  return (
    <QueryClientProvider client={{queryClient}}>
      <MemoryRouter>{{children}}</MemoryRouter>
    </QueryClientProvider>
  )
}}

// ── Card Component ──

describe('Card', () => {{
  it('renders children', () => {{
    render(<Card><span>Hello</span></Card>, {{ wrapper: Wrapper }})
    expect(screen.getByText('Hello')).toBeDefined()
  }})

  it('applies variant classes', () => {{
    const {{ container }} = render(<Card variant="elevated">Test</Card>, {{ wrapper: Wrapper }})
    expect(container.firstChild).toBeDefined()
  }})
}})

// ── Button Component ──

describe('Button', () => {{
  it('renders with text', () => {{
    render(<Button>Click me</Button>, {{ wrapper: Wrapper }})
    expect(screen.getByText('Click me')).toBeDefined()
  }})

  it('renders loading state', () => {{
    render(<Button loading>Loading</Button>, {{ wrapper: Wrapper }})
    expect(screen.getByText('Loading')).toBeDefined()
  }})

  it('handles click', () => {{
    let clicked = false
    render(<Button onClick={{() => {{ clicked = true }}}}>Click</Button>, {{ wrapper: Wrapper }})
    screen.getByText('Click').click()
    expect(clicked).toBe(true)
  }})
}})

// ── Input Component ──

describe('Input', () => {{
  it('renders with label', () => {{
    const {{ container }} = render(<Input label="Email" />, {{ wrapper: Wrapper }})
    expect(screen.getByText('Email')).toBeDefined()
  }})

  it('shows error message', () => {{
    render(<Input label="Email" error="Invalid email" />, {{ wrapper: Wrapper }})
    expect(screen.getByText('Invalid email')).toBeDefined()
  }})

  it('shows required indicator', () => {{
    render(<Input label="Name" required />, {{ wrapper: Wrapper }})
    expect(screen.getByText('*')).toBeDefined()
  }})
}})

// ── EmptyState Component ──

describe('EmptyState', () => {{
  it('renders title', () => {{
    render(<EmptyState title="No items" />, {{ wrapper: Wrapper }})
    expect(screen.getByText('No items')).toBeDefined()
  }})

  it('renders description', () => {{
    render(<EmptyState title="Empty" description="Nothing here" />, {{ wrapper: Wrapper }})
    expect(screen.getByText('Nothing here')).toBeDefined()
  }})
}})

// ── Skeleton Component ──

describe('Skeleton', () => {{
  it('renders with animate class', () => {{
    const {{ container }} = render(<Skeleton />, {{ wrapper: Wrapper }})
    expect(container.firstChild).toBeDefined()
  }})
}})
'''


# ── 10K Components ────────────────────────────────────

def _theme_toggle() -> str:
    return """import { useTheme } from '../hooks/useTheme'

export function ThemeToggle() {
  const { theme, cycleTheme } = useTheme()

  const icons: Record<string, JSX.Element> = {
    system: (
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 17.25v1.007a3 3 0 01-.879 2.122L7.5 21h9l-.621-.621A3 3 0 0115 18.257V17.25m6-12V15a2.25 2.25 0 01-2.25 2.25H5.25A2.25 2.25 0 013 15V5.25m18 0A2.25 2.25 0 0018.75 3H5.25A2.25 2.25 0 003 5.25m18 0V12a2.25 2.25 0 01-2.25 2.25H5.25A2.25 2.25 0 013 12V5.25" />
      </svg>
    ),
    dark: (
      <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
        <path d="M21.752 15.002A9.718 9.718 0 0118 15.75c-5.385 0-9.75-4.365-9.75-9.75 0-1.33.266-2.597.748-3.752A9.753 9.753 0 003 11.25C3 16.635 7.365 21 12.75 21a9.753 9.753 0 009.002-5.998z" />
      </svg>
    ),
    light: (
      <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
        <path d="M12 2.25a.75.75 0 01.75.75v2.25a.75.75 0 01-1.5 0V3a.75.75 0 01.75-.75zM7.5 12a4.5 4.5 0 119 0 4.5 4.5 0 01-9 0zM18.894 6.166a.75.75 0 00-1.06-1.06l-1.591 1.59a.75.75 0 101.06 1.061l1.591-1.59zM21.75 12a.75.75 0 01-.75.75h-2.25a.75.75 0 010-1.5H21a.75.75 0 01.75.75zM17.834 18.894a.75.75 0 001.06-1.06l-1.59-1.591a.75.75 0 10-1.061 1.06l1.59 1.591zM12 18a.75.75 0 01.75.75V21a.75.75 0 01-1.5 0v-2.25A.75.75 0 0112 18zM7.758 17.303a.75.75 0 00-1.061-1.06l-1.591 1.59a.75.75 0 001.06 1.061l1.591-1.59zM6 12a.75.75 0 01-.75.75H3a.75.75 0 010-1.5h2.25A.75.75 0 016 12zM6.697 7.757a.75.75 0 001.06-1.06l-1.59-1.591a.75.75 0 00-1.061 1.06l1.59 1.591z" />
      </svg>
    ),
  }

  return (
    <button
      onClick={cycleTheme}
      className="p-2 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors text-slate-600 dark:text-slate-300"
      aria-label={`Theme: ${theme}`}
      title={`Theme: ${theme}`}
    >
      {icons[theme]}
    </button>
  )
}
"""


def _language_switcher() -> str:
    return """import { useTranslation } from '../i18n'

export function LanguageSwitcher() {
  const { lang, setLang, availableLangs } = useTranslation()

  return (
    <div className="flex items-center gap-1">
      {availableLangs.map(l => (
        <button
          key={l}
          onClick={() => setLang(l)}
          className={`px-2 py-1 text-xs font-medium rounded transition-colors ${
            lang === l
              ? 'bg-teal-100 dark:bg-teal-500/10 text-teal-700 dark:text-teal-400'
              : 'text-slate-500 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800'
          }`}
          aria-label={`Switch to ${l}`}
        >
          {l.toUpperCase()}
        </button>
      ))}
    </div>
  )
}
"""


def _card_component() -> str:
    return """import { ReactNode } from 'react'

interface CardProps {
  children: ReactNode
  className?: string
  variant?: 'default' | 'outlined' | 'elevated'
  hover?: boolean
  onClick?: () => void
}

const variants = {
  default: 'bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700',
  outlined: 'bg-transparent border-2 border-slate-200 dark:border-slate-700',
  elevated: 'bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 shadow-lg',
}

export function Card({ children, className = '', variant = 'default', hover = false, onClick }: CardProps) {
  return (
    <div
      className={`rounded-xl p-6 ${variants[variant]} ${hover ? 'hover:border-teal-500/50 hover:shadow-md transition-all duration-200' : ''} ${onClick ? 'cursor-pointer' : ''} ${className}`}
      onClick={onClick}
    >
      {children}
    </div>
  )
}
"""


def _modal_component() -> str:
    return """import { ReactNode, useEffect, useRef } from 'react'

interface ModalProps {
  isOpen: boolean
  onClose: () => void
  title: string
  children: ReactNode
}

export function Modal({ isOpen, onClose, title, children }: ModalProps) {
  useEffect(() => {
    const handleEsc = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose() }
    if (isOpen) {
      document.addEventListener('keydown', handleEsc)
      document.body.style.overflow = 'hidden'
    }
    return () => {
      document.removeEventListener('keydown', handleEsc)
      document.body.style.overflow = ''
    }
  }, [isOpen, onClose])

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/50 backdrop-blur-sm" onClick={onClose} />
      <div className="relative bg-white dark:bg-slate-800 rounded-2xl shadow-xl max-w-lg w-full max-h-[85vh] overflow-auto">
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 dark:border-slate-700">
          <h2 className="text-lg font-semibold text-slate-900 dark:text-white">{title}</h2>
          <button onClick={onClose} className="p-2 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-700" aria-label="Close">
            <svg className="w-5 h-5 text-slate-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        <div className="p-6">{children}</div>
      </div>
    </div>
  )
}
"""


def _toast_component() -> str:
    return """import { createContext, useContext, useState, useCallback, ReactNode } from 'react'

type ToastType = 'success' | 'error' | 'warning' | 'info'

interface Toast { id: number; type: ToastType; message: string }

interface ToastContextType { addToast: (type: ToastType, message: string) => void }

const ToastContext = createContext<ToastContextType>({ addToast: () => {} })

export function useToast() { return useContext(ToastContext) }

let toastId = 0

export function ToastProvider({ children }: { children: ReactNode }) {
  const [toasts, setToasts] = useState<Toast[]>([])

  const addToast = useCallback((type: ToastType, message: string) => {
    const id = ++toastId
    setToasts(prev => [...prev, { id, type, message }])
    setTimeout(() => setToasts(prev => prev.filter(t => t.id !== id)), 4000)
  }, [])

  const colors: Record<ToastType, string> = {
    success: 'bg-green-50 dark:bg-green-500/10 border-green-200 dark:border-green-500/20 text-green-800 dark:text-green-400',
    error: 'bg-red-50 dark:bg-red-500/10 border-red-200 dark:border-red-500/20 text-red-800 dark:text-red-400',
    warning: 'bg-amber-50 dark:bg-amber-500/10 border-amber-200 dark:border-amber-500/20 text-amber-800 dark:text-amber-400',
    info: 'bg-blue-50 dark:bg-blue-500/10 border-blue-200 dark:border-blue-500/20 text-blue-800 dark:text-blue-400',
  }

  return (
    <ToastContext.Provider value={{ addToast }}>
      {children}
      <div className="fixed bottom-4 right-4 z-50 space-y-2">
        {toasts.map(toast => (
          <div key={toast.id} className={`flex items-center gap-3 px-4 py-3 rounded-xl border shadow-lg ${colors[toast.type]}`}>
            <span className="text-sm font-medium">{toast.message}</span>
          </div>
        ))}
      </div>
    </ToastContext.Provider>
  )
}
"""


def _button_component() -> str:
    return """import { ReactNode, ButtonHTMLAttributes } from 'react'

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  children: ReactNode
  variant?: 'primary' | 'secondary' | 'outline' | 'ghost'
  size?: 'sm' | 'md' | 'lg'
  loading?: boolean
}

const variants = {
  primary: 'bg-teal-600 hover:bg-teal-500 text-white shadow-sm',
  secondary: 'bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300',
  outline: 'border border-slate-300 dark:border-slate-600 hover:bg-slate-50 dark:hover:bg-slate-800 text-slate-700 dark:text-slate-300',
  ghost: 'hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-600 dark:text-slate-400',
}

const sizes = { sm: 'px-3 py-1.5 text-xs', md: 'px-4 py-2 text-sm', lg: 'px-6 py-3 text-base' }

export function Button({ children, variant = 'primary', size = 'md', loading = false, disabled, className = '', ...props }: ButtonProps) {
  return (
    <button className={`inline-flex items-center justify-center gap-2 rounded-lg font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed ${variants[variant]} ${sizes[size]} ${className}`} disabled={disabled || loading} {...props}>
      {loading && <svg className="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" /><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" /></svg>}
      {children}
    </button>
  )
}
"""


def _input_component() -> str:
    return """import { InputHTMLAttributes, forwardRef } from 'react'

interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
  label?: string
  error?: string
  hint?: string
}

export const Input = forwardRef<HTMLInputElement, InputProps>(({ label, error, hint, className = '', ...props }, ref) => {
  return (
    <div className="space-y-1">
      {label && <label className="block text-sm font-medium text-slate-700 dark:text-slate-300">{label}{props.required && <span className="text-red-500 ml-1">*</span>}</label>}
      <input ref={ref} className={`w-full rounded-lg border bg-white dark:bg-slate-800 px-3 py-2 text-sm text-slate-900 dark:text-slate-100 placeholder-slate-400 transition-colors focus:outline-none focus:ring-2 focus:ring-teal-500/20 focus:border-teal-500 ${error ? 'border-red-300 dark:border-red-500/50' : 'border-slate-300 dark:border-slate-600'} ${className}`} {...props} />
      {error && <p className="text-xs text-red-500 mt-1">{error}</p>}
      {hint && !error && <p className="text-xs text-slate-400 mt-1">{hint}</p>}
    </div>
  )
})

Input.displayName = 'Input'
"""


def _skeleton_component() -> str:
    return """interface SkeletonProps { className?: string; variant?: 'text' | 'circular' | 'rectangular'; width?: string | number; height?: string | number }

export function Skeleton({ className = '', variant = 'text', width, height }: SkeletonProps) {
  return <div className={`animate-pulse bg-slate-200 dark:bg-slate-700 rounded ${className}`} style={{ width, height }} />
}
"""


def _empty_state_component() -> str:
    return """import { ReactNode } from 'react'

interface EmptyStateProps { icon?: ReactNode; title: string; description?: string; action?: ReactNode }

export function EmptyState({ icon, title, description, action }: EmptyStateProps) {
  return (
    <div className="flex flex-col items-center justify-center py-16 px-4 text-center">
      {icon || <div className="w-16 h-16 rounded-2xl bg-slate-100 dark:bg-slate-800 flex items-center justify-center mb-4"><svg className="w-8 h-8 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4" /></svg></div>}
      <h3 className="text-lg font-semibold text-slate-900 dark:text-white mb-1">{title}</h3>
      {description && <p className="text-sm text-slate-500 dark:text-slate-400 max-w-sm mb-4">{description}</p>}
      {action}
    </div>
  )
}
"""


def _error_boundary() -> str:
    return """import { Component, ReactNode } from 'react'
import { EmptyState } from './EmptyState'
import { Button } from './Button'

interface Props { children: ReactNode; fallback?: ReactNode }
interface State { hasError: boolean; error?: Error }

export class ErrorBoundary extends Component<Props, State> {
  state: State = { hasError: false }
  static getDerivedStateFromError(error: Error): State { return { hasError: true, error } }
  render() {
    if (this.state.hasError) {
      return <EmptyState title="Something went wrong" description={this.state.error?.message} action={<Button variant="secondary" onClick={() => this.setState({ hasError: false })}>Try again</Button>} />
    }
    return this.props.children
  }
}
"""


def _table_component() -> str:
    return """import { useState } from 'react'

interface Column<T> { key: string; header: string; sortable?: boolean; render?: (item: T) => React.ReactNode }
interface TableProps<T> { columns: Column<T>[]; data: T[]; loading?: boolean; emptyMessage?: string; onRowClick?: (item: T) => void }

export function Table<T extends Record<string, unknown>>({ columns, data, loading = false, emptyMessage = 'No items found', onRowClick }: TableProps<T>) {
  const [sortKey, setSortKey] = useState<string | null>(null)
  const [sortDir, setSortDir] = useState<'asc' | 'desc'>('asc')

  if (loading) return <div className="rounded-xl border border-slate-200 dark:border-slate-700 p-8 text-center text-slate-400">Loading...</div>
  if (data.length === 0) return <div className="rounded-xl border border-slate-200 dark:border-slate-700 p-8 text-center text-slate-400">{emptyMessage}</div>

  return (
    <div className="rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden">
      <table className="w-full">
        <thead>
          <tr className="bg-slate-50 dark:bg-slate-800/50 border-b border-slate-200 dark:border-slate-700">
            {columns.map(col => (
              <th key={col.key} onClick={() => col.sortable && setSortKey(sortKey === col.key ? null : col.key)} className={`px-4 py-3 text-left text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider ${col.sortable ? 'cursor-pointer hover:text-slate-700' : ''}`}>
                {col.header}{col.sortable && sortKey === col.key && <span className="ml-1">{sortDir === 'asc' ? '\u2191' : '\u2193'}</span>}
              </th>
            ))}
          </tr>
        </thead>
        <tbody className="divide-y divide-slate-100 dark:divide-slate-700/50">
          {data.map((item, idx) => (
            <tr key={idx} className={`hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors ${onRowClick ? 'cursor-pointer' : ''}`} onClick={() => onRowClick?.(item)}>
              {columns.map(col => <td key={col.key} className="px-4 py-3 text-sm text-slate-600 dark:text-slate-300">{col.render ? col.render(item) : String(item[col.key] ?? '')}</td>)}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}
"""
