"""PDF export routes — premium editorial PDF generation with signed URLs.

TASK-054: Professional PDF export with:
- Editorial layout (cover, TOC, headers/footers, page numbers)
- Watermark support (CONFIDENTIAL / DRAFT)
- Brand customization (colors, logo, company name)
- Signed temporary download URLs (HMAC-SHA256)
- Multiple document types: pitch deck, planning report, landing page
"""

import json
import logging
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import FileResponse, JSONResponse

from ..database import Project, ResearchResult, Job
from ..services.pdf_export import (
    generate_pdf,
    generate_signed_url,
    verify_signed_url,
    build_pitch_deck_html,
    build_planning_report_html,
)
from ..utils.paths import GENERATED_DIR

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/pdf", tags=["pdf"])


# ── Document Types ─────────────────────────────────────

DOC_TYPES = {
    "pitch-deck": {
        "label": "Pitch Deck",
        "description": "Professional investment pitch deck with competitive analysis",
        "filename": "pitch-deck.pdf",
        "icon": "📊",
    },
    "planning-report": {
        "label": "Planning Report",
        "description": "Full planning report: PRD, Functional, Financial, Technical specs",
        "filename": "planning-report.pdf",
        "icon": "📋",
    },
    "landing": {
        "label": "Landing Page",
        "description": "Marketing landing page as PDF",
        "filename": "landing.pdf",
        "icon": "🌐",
    },
}


@router.get("/types")
async def get_document_types():
    """List available PDF document types with descriptions."""
    return {"types": DOC_TYPES}


@router.post("/generate/{project_id}/{doc_type}")
async def generate_document_pdf(
    project_id: str,
    doc_type: str,
    watermark: str = Query("", description="'CONFIDENTIAL' or 'DRAFT' for watermark overlay"),
    brand_name: str = Query("PitchForge", description="Brand name for header"),
    primary_color: str = Query("#0d9488", description="Primary brand color (hex)"),
    company: str = Query("", description="Company name for cover"),
):
    """Generate a professional PDF for a document type with optional watermark and branding.

    Returns a signed URL that can be used to download the PDF within 24 hours.
    """
    if doc_type not in DOC_TYPES:
        raise HTTPException(status_code=404, detail=f"Unknown document type: {doc_type}. Available: {list(DOC_TYPES.keys())}")

    # Validate watermark
    VALID_WATERMARKS = {"", "CONFIDENTIAL", "DRAFT"}
    if watermark.upper() not in VALID_WATERMARKS:
        raise HTTPException(status_code=400, detail=f"Invalid watermark: '{watermark}'. Must be 'CONFIDENTIAL', 'DRAFT', or empty.")

    # Load project & research data
    project = await Project.find_one(Project.id == project_id)
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")

    research = await ResearchResult.find_one(ResearchResult.project_id == project_id)
    if not research or not research.report_json:
        raise HTTPException(status_code=404, detail="No research data found for this project")

    report_json = research.report_json
    if isinstance(report_json, str):
        report_json = json.loads(report_json)

    # Build content based on doc type
    brand = {
        "primary_color": primary_color,
        "secondary_color": _darken_hex(primary_color),
        "brand_name": brand_name,
        "company": company,
        "watermark_color": "#dc2626" if watermark else "#94a3b8",
    }

    title = f"{DOC_TYPES[doc_type]['label']}: {project.title or report_json.get('idea', '')}"
    subtitle = report_json.get("recommended_positioning", "") or report_json.get("summary", "")[:120] or "Generated by PitchForge"

    # Prepare output directory
    out_dir = GENERATED_DIR / project_id / "pdf"
    out_dir.mkdir(parents=True, exist_ok=True)

    # Get HTML content
    html_content = ""
    if doc_type == "pitch-deck":
        html_content = build_pitch_deck_html(report_json)
    elif doc_type == "planning-report":
        # Try to load latest planning output
        jobs = await Job.find(
            Job.project_id == project_id,
            Job.type == "planning",
            Job.status == "complete",
        ).sort(-Job.created_at).limit(1).to_list()
        if jobs and jobs[0].result and jobs[0].result.get("output_dir"):
            # Load from planning report JSON
            from pathlib import Path
            plan_json = Path(jobs[0].result["output_dir"]) / "planning_report.json"
            if plan_json.exists():
                planning_data = json.loads(plan_json.read_text())
                html_content = build_planning_report_html(planning_data)
            else:
                # Try result payload
                if jobs[0].result.get("planning_output"):
                    planning_data = jobs[0].result["planning_output"]
                    if isinstance(planning_data, str):
                        planning_data = json.loads(planning_data)
                    html_content = build_planning_report_html(planning_data)
                else:
                    raise HTTPException(status_code=400, detail="No planning data found. Run Planning first before exporting as PDF.")
        else:
            raise HTTPException(status_code=400, detail="No planning data found. Run Planning first before exporting as PDF.")
    elif doc_type == "landing":
        # Find generated landing page HTML
        landing_path = await _find_asset_file(project_id, "landing")
        if landing_path:
            html_content = landing_path.read_text(encoding="utf-8")
        else:
            html_content = f"<h2 class='section'>Landing Page: {_esc(title)}</h2><p>{_esc(report_json.get('summary', ''))}</p>"

    # Generate PDF
    filename = DOC_TYPES[doc_type]["filename"]
    pdf_path = generate_pdf(
        html_content=html_content,
        title=title,
        subtitle=subtitle,
        watermark=watermark,
        brand=brand,
        output_dir=out_dir,
        filename=filename,
    )

    if not pdf_path or not pdf_path.exists():
        raise HTTPException(status_code=500, detail="PDF generation failed. WeasyPrint may not be installed.")

    # Generate signed URL
    signed_url = generate_signed_url(project_id, doc_type)

    return {
        "status": "complete",
        "project_id": project_id,
        "doc_type": doc_type,
        "filename": filename,
        "size_bytes": pdf_path.stat().st_size,
        "download_url": signed_url,
        "expires_in_hours": 24,
    }


@router.get("/download/{project_id}/{doc_type}")
async def download_pdf(
    project_id: str,
    doc_type: str,
    expires: int = Query(...),
    sig: str = Query(...),
):
    """Download a PDF using a signed URL (generated by POST /generate)."""
    # Verify signed URL
    if not verify_signed_url(project_id, doc_type, expires, sig):
        raise HTTPException(status_code=403, detail="Invalid or expired download URL")

    # Find the PDF file
    pdf_path = GENERATED_DIR / project_id / "pdf" / DOC_TYPES[doc_type]["filename"]
    if not pdf_path.exists():
        raise HTTPException(status_code=404, detail="PDF not found. Generate it first via POST /generate")

    return FileResponse(
        path=str(pdf_path),
        filename=DOC_TYPES[doc_type]["filename"],
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="{DOC_TYPES[doc_type]["filename"]}"',
        },
    )


# ── Helpers ────────────────────────────────────────────

async def _find_asset_file(project_id: str, name: str) -> Optional[Path]:
    """Find a generated asset file (landing.html, pitch_deck.html, etc.)."""
    # Check project's assets_output_dir
    project = await Project.find_one(Project.id == project_id)
    if not project:
        return None

    search_dirs = []
    if project.assets_output_dir:
        search_dirs.append(Path(project.assets_output_dir))
        search_dirs.append(Path(project.assets_output_dir) / "assets")
    if project.planning_output_dir:
        search_dirs.append(Path(project.planning_output_dir))

    for base_dir in search_dirs:
        if not base_dir.exists():
            continue
        for sub in ["", "assets"]:
            candidate = base_dir / sub / f"{name}.html"
            if candidate.exists():
                return candidate

    return None


def _esc(text: str) -> str:
    """HTML-escape a string."""
    if not text:
        return ""
    return (text.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace('"', "&quot;")
                .replace("'", "&#39;"))


def _darken_hex(hex_color: str) -> str:
    """Darken a hex color for use as secondary brand color."""
    hex_color = hex_color.lstrip("#")
    if len(hex_color) != 6:
        return "#155e75"
    try:
        r, g, b = int(hex_color[0:2], 16), int(hex_color[2:4], 16), int(hex_color[4:6], 16)
        factor = 0.7
        r = max(0, min(255, int(r * factor)))
        g = max(0, min(255, int(g * factor)))
        b = max(0, min(255, int(b * factor)))
        return f"#{r:02x}{g:02x}{b:02x}"
    except ValueError:
        return "#155e75"
